version: '3.4'
services:
  eureka-server:
    container_name: eureka-server
    image: eureka-server
    build: ./EurekaServer
    ports:
      - 8084:8084
    networks:
      - microservices-tecsup
  config-server:
    container_name: config-server
    image: config-server
    build: ./ConfigServer
    ports:
      - 8889:8889
    healthcheck:
      test: "curl http://config-server:8889/productos-api/dev"
      interval: 10s
      timeout: 2s
      retries: 3
    networks:
      - microservices-tecsup
  dbmysql:
    container_name: dbmysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: tiendaapi
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/data
      - ./database/tiendaapi.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - 3306:3306
    networks:
      - microservices-tecsup
  productos-api:
    container_name: productos-api
    image: productos-api
    build: ./productos-api
    restart: always
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8084/eureka/
      - CONFIG_SERVER_URI=http://config-server:8889
      - server.port=8082
    depends_on:
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
      dbmysql:
        condition: service_started
    networks:
      - microservices-tecsup
    ports:
      - 8082:8082
volumes:
  db-data:
networks:
  microservices-tecsup:
